### ISSUE TITLE
Bullet points used in Phase description are not real bullet points

### ISSUE THREAD

**Issue by msvoelker** [nplab/plpmtud#10]
The bullet points in the Phase section read like normal sentences. For example, when using bullet points, we should avoid referencing to a previous bullet point (with Then, ... or Once confirmed, ...). Bullet points are an unordered list for me.

My suggestion is either we remove the bullet point symbols (use the normal sentences as they are) or we rewrite it (this corresponds to point 3 of issue #4).

Here is the current Base Phase description.

> Base Phase
> 
> * The Base Phase confirms connectivity to the remote peer. This phase is implicit for a connection-oriented PL (where it can be performed in a PL connection handshake). A connectionless PL needs to send an acknowledged probe packet to confirm that the remote peer is reachable.
> * The sender also confirms that BASE_PMTU is supported across the network path.
> * A PL that does not wish to support a path with a PLPMTU less than BASE_PMTU can simplify the phase into a single step by performing the connectivity checks with a probe of the BASE_PMTU size.
> * Once confirmed, DPLPMTUD enters the Search Phase. If this phase fails to confirm, DPLPMTUD enters the Error Phase.

This is how I would write it, when using bullet points.

> Base Phase
> 
> * Confirms connectivity to the remote peer
> Note: This is implicit for a connection-oriented PL (where it can be performed in a PL connection handshake). A connectionless PL needs to send an acknowledged probe packet to confirm that the remote peer is reachable.
> * Confirms BASE_PMTU support across the network path
> Note: A PL that does not wish to support a path with a PLPMTU less than BASE_PMTU can simplify the phase into a single step by performing the connectivity checks with a probe of the BASE_PMTU size.
> * Enters Search phase on success
> * Enters Error phase on failure

**Comment by msvoelker** [comment]
I forgot to mention, that when I change the text, I will remove this bullet point from Search Phase, since it describes a transition that is not in the diagram (corresponds to point 4 of issue #4).

> Black hole detection can also terminate the search by entering the Base phase.

I also forgot to add your names
@adventureloop @gorryfair

**Comment by gorryfair** [comment]
So I think the original looks ok, and the bullets seem fine to me. Would it seem better to you to use numbers rather than bullets - what would seem best, they do not make much difference to me, or we could remove the bullets and just leave sentences?

**Comment by msvoelker** [comment]
Removing the bullet points and leaving the sentences as they are, is fine to me. I just did it.

I also ...

... removed following sentence in Search Phase description, since it describes a Phase transition that is not depicted in the diagram.

> Black Hole Detection can also terminate the search by entering the BASE_PMTU Confirmation phase.

... moved the following sentence from Error Phase description to Error State description, since MIN_PMTU is not mentioned in the Phase description.

> Note: MIN_PMTU may be identical to BASE_PMTU, simplifying the actions in this phase.

If this looks fine to you, we can close this issue.
