### ISSUE TITLE
Section Packetization Layer Path MTU Discovery - more straight forward

### ISSUE THREAD

**Issue by msvoelker** [nplab/plpmtud#2]
This is currently the last paragraph of section 1.2. Section Packetization Layer Path MTU Discovery:

PLPMTUD can also include additional consistency checks without increasing the risk of increased black-holing. For instance, the information available at the PL, or higher layers, makes PTB message validation more straight forward.

What does 

> without increasing the risk of increased black-holing

mean and what does 

> more straight forward

mean? Can we make it more clear?

**Comment by gorryfair** [comment]
/without increasing the risk of increased black-holing/without increasing the risk that data is lost when probing to discover the path MTU/.

/ makes PTB message validation more straight forward./enables PTB messages to be validating utilizing information available at the transport layer./

**Comment by msvoelker** [comment]
OK, then we have

PLPMTUD can also include additional consistency checks without increasing the risk that data is lost when probing to discover the path MTU. For instance, the information available at the PL, or higher layers, enables PTB messages to be validating utilizing information available at the transport layer.

With that, I got a better idea of what this paragraph tries to tell. The last sentence now contains a third name for the layer (transport). How about

/enables PTB messages to be validating utilizing information available at the transport layer/enables PTB messages to be validating utilizing these information

OK?

**Comment by gorryfair** [comment]
I'm OK with:

/For example, information available at the PL, or higher layers, enables received PTB messages to be validated before being utilized./

**Comment by msvoelker** [comment]
committed
