### ISSUE TITLE
Rewrite section Detection of Black Holes

### ISSUE THREAD

**Issue by msvoelker** [nplab/plpmtud#3]
I think we can describe the detection of black holes more to the point. This is my suggestion for section 4.3. Detection of Black Holes:

A PL sender encounters a black hole, if its sent packets are silently discarded without receiving a notification (e. g. a PTB message). This happens, for instance, if the sender keeps sending packets with a size of PLPMTU while the PMTU changed to a value less than PLPMTU. To avoid massive packet loss, it is crucial for the DPLPMTUD sender to detect a black hole as fast as possible.

There are two ways to detect that the current PLPMTU is not sustained by the path (i. e. to detect a black hole):
* A PL can rely upon a mechanism implemented within the PL protocol to detect excessive loss of data sent with a specific packet size and then conclude that this excessive loss could be a result of an invalid PMTU (as in PLPMTUD for TCP [RFC4821]).
* A PL can use the probing mechanism to send confirmation probe packets of the size of the current PLPMTU and a timer track whether acknowledgments are received. After a number of successive probe packets sent without receiving an acknowledgement, the PL can conclude that this is due to a black hole (the CONFIRMATION_TIMER is used to periodically confirm the current PLPMTU, see Section 5.1.1).

When the method detects the current PLPMTU is not supported (a black hole is found), DPLPMTUD sets a lower MPS. The PL then confirms that the updated PLPMTU can be successfully used across the path. This can need the PL to send a probe packet with a size less than the size of the data block generated by an application. In this case, the PL could provide a way to fragment a datagram at the PL, or could instead utilize a control packet with padding.

**Comment by gorryfair** [comment]
This new English doesn't parse for me. And I have issues with various parts of this text.

First, we need to decide what "black hole" means. 
• You seem to interpet this as " if its sent packets are silently discarded without receiving a notification (e. g. a PTB message).", this excludes when the current PLPMTU fails to work because it reduced and you received a PTB mesage.
•  whereas I defined this as the data with the current PLPMTU dissappears, irrespective of how you discover the data loss. That means if you previously grew the PLPMTU and it reduced, it could be black-holed.

These two definitions are different.

**Comment by msvoelker** [comment]
> This new English doesn't parse for me.

It parses for me, but I guess your parser is the better one :-)

> First, we need to decide what "black hole" means.

Totally agree. My first intention was that a black hole is something where things go in and disappear without anything coming back from the black hole. To not solely rely on my intention I looked in our Terminology section and in the RFCs 4821 and 2923. All seem to agree with my first intention.

**Comment by gorryfair** [comment]
I suggest to avoid this, we do not change the text, but we do change the section title, reflecting that this is when the current PLPMTU is not supported.

**Comment by msvoelker** [comment]
OK for me, but I fear we can't leave the text as it is. We need at least replace "black hole" in the text. Here is my suggestion for this section.

```
<section anchor="mechanism-bhd" title="Detect Unsupported PLPMTU Size">
<t>A PL sender needs to reduce the PLPMTU when it discovers the actual
PMTU supported by a network path is less than the PLPMTU. There are three
ways a DPLPMTUD sender detect that the current PLPMTU is not sustained
by the path.

<t><list style="symbols">
	<t>A PL can rely upon a mechanism implemented within the PL
	protocol to detect excessive loss of data sent with a specific
	packet size and then conclude that this excessive loss could be a
	result of an invalid PMTU (as in PLPMTUD for TCP <xref
	target="RFC4821"></xref>).</t>

	<t>A PL can use the probing mechanism to send confirmation probe
	packets of the size of the current PLPMTU and a timer track
	whether acknowledgments are received. These messages need to be
	generated periodically (e.g., using the confirmation timer <xref
	target="Timers"></xref>).
	Successive loss of probes (e.g., the number of probe
	packets sent without receiving an acknowledgement, PROBE_COUNT,
	reaches MAX_PROBES) is an indication that the current path
	no longer supports the PLPMTU.</t>

	<t>A PL can use a PTB message that reports a MTU (PTB_SIZE) less than PLPMTU. 
	The receiver needs to validate the PTB message first. The response
	to it depends on PTB_SIZE (see <xref target="echanism-ptb" />).</t>
  </list></t>

<t>When the method detects the current PLPMTU is not supported,
DPLPMTUD sets a lower MPS. The PL then confirms
that the updated PLPMTU can be successfully used across the path. This
can need the PL to send a probe packet with a size less than the size
of the data block generated by an application. In this case, the PL
could provide a way to fragment a datagram at the PL, or could instead
utilize a control packet with padding.</t>
</section>
```

**Comment by adventureloop** [comment]
I can read rfc2923 both ways:

      PMTUD, as documented in [RFC1191], fails when the appropriate ICMP
      messages are not received by the originating host.  The upper-
      layer protocol continues to try to send large packets and, without
      the ICMP messages, never discovers that it needs to reduce the
      size of those packets.  Its packets are disappearing into a PMTUD
      black hole.

We have 2 types of black hole.
**ICMP Black Hole:**
    
    The upper-layer protocol continues to try to send large packets and, without
    the ICMP messages, never discovers that it needs to reduce the
    size of those packets.

**PMTU Black Hole:**

    Its packets are disappearing into a PMTUD black hole.

We don't really care about the first without the second, we have to handle both. So far I think we have designed to support having both black holes and only PMTU black holes. Can we keep the term black hole to cover both and add some explaination? If so can we go back to the original section heading?

**Comment by gorryfair** [comment]
• I agree with the above,  and think we should anyway clarify the two types of black hole. Noting that either of these can result in classic PMTUD failing and not detecting the incorrect PMTU, but PLPMTUD is able to detect an inappropriate PLPMTU  and choose a suitable value.

• I'd prefer to call the bottom one a "Packet Black Hole" or something similar.

• I'm still OK with changing the wording of the title and making careful edits throughout  - but probably favour the change proposed by Tom to clarify the intent in this document, not least because this would resolve the ambiguity in a simpler way.

**Comment by msvoelker** [comment]
I read section 2.1 of rfc2923 again. I still don't see a second definition for a black hole. They used the term ICMP Black Hole in this section as well, but my understanding is that they used it as a synonym for PMTUD Black Hole.

However, we still could define a second definition and name it, for example, PLPMTUD Black Hole. But I don't think that helps us much. It would be a superset of PMTUD Black Hole, which includes the case where we get a PTB message in response. I think, it helps more to have mutual exclusive definitions. 

When we send a packet with a size larger than PMTU, two cases are possible.
* We experience a PMTUD Black Hole and get no response.
* We used a regular path and receive a PTB in response.

That's not very complex. I don't think we need an extra definition for that (our state diagram already distinguishes between these two cases).

In a good tradition, I suggest a new text for this section :-)

```
<section anchor="mechanism-bhd" title="Detection of Black Holes">
<t>A PL sender needs to reduce the PLPMTU when it discovers the actual
PMTU supported by a network path is less than the PLPMTU. For example,
this can be triggered when a validated PTB message is received (see section 4.4.2).
However, if the sent packets were lost in a PMTUD Black Hole, no PTB message
arrive at the sender. In this case there are two ways a DPLPMTUD
sender detect that the current PLPMTU is not sustained by the path.

<t><list style="symbols">
	<t>A PL can rely upon a mechanism implemented within the PL
	protocol to detect excessive loss of data sent with a specific
	packet size and then conclude that this excessive loss could be a
	result of an invalid PMTU (as in PLPMTUD for TCP <xref
	target="RFC4821"></xref>).</t>

	<t>A PL can use the probing mechanism to send confirmation probe
	packets of the size of the current PLPMTU and a timer track
	whether acknowledgments are received. These messages need to be
	generated periodically (e.g., using the confirmation timer <xref
	target="Timers"></xref>).
	Successive loss of probes (e.g., the number of probe
	packets sent without receiving an acknowledgement, PROBE_COUNT,
	reaches MAX_PROBES) is an indication that the current path
	no longer supports the PLPMTU.</t>
  </list></t>

<t>When the method detects the current PLPMTU is not supported,
DPLPMTUD sets a lower MPS. The PL then confirms
that the updated PLPMTU can be successfully used across the path. This
can need the PL to send a probe packet with a size less than the size
of the data block generated by an application. In this case, the PL
could provide a way to fragment a datagram at the PL, or could instead
utilize a control packet with padding.</t>
</section>
```

**Comment by gorryfair** [comment]
I will soon post a new rev to address this issue after reviewing this text and other feedback from transport people at the QUIC interim yesterday.

**Comment by msvoelker** [comment]
I still don't like to have two black hole definitions. I also don't see the concept behind the names. If I would read the names for the first time, I probably would assume the following

Packet Black Hole - Black Hole that absorbs all kind of packets.
ICMP Black Hole - Black Hole that absorbs only ICMP packets.

which is not true.

I suggest to avoid having the first definition and use the name PMTUD Black Hole for the latter. I like the name PMTUD Black Hole more, because it indicates that the packet drop has something to do with the packet size and that PMTUD gets no repsponse (= no PTB).

If you follow my one Black Hole definition way, we should use my last suggested text for the black hole detection section (in my previous comment here). I wrote it in a way that allows us to keep the original title.

Since you (@adventureloop / @gorryfair) added the second black hole definition to the draft, I guess you are not convinced by a one and only Black Hole definition. If you both strongly believe, we need two definitions and the names are perfect as they are, then we can just close this issue.

**Comment by msvoelker** [comment]
My understanding is, you want two definitions. Then, let's go for it.
