### ISSUE TITLE
Remove or change section DPLPMTUD Phases

### ISSUE THREAD

**Issue by msvoelker** [nplab/plpmtud#4]
As far as I understand, we have the phases section to describe the DPLPMTUD method on a higher level than the state diagram section does. I like that, but do we need the term Phases? People could be confused and might think phases are another concept besides the states. Additionally it seems this section was written with less love than the rest of the draft.

Is the state machine so complex that we really need a high level description beforehand?

@tuexen suggested, if we want a high level description, why not name it Simplified State Machine to avoid using the term Phase.

**Comment by gorryfair** [comment]
The term "phase" seems appropriate here to me. Phases do describe operation at a higher level than the concerte states. We can add a sentence that says so.

**Comment by msvoelker** [comment]
I silently hoped we can remove this section, because I see quite a few issues in the text. Here is a summary.

1. Diagram: Remove arrow from Error to BASE_PMTU Confirmation and add an arrow from Error to Search with the condition "BASE_PMTU confirmed". 
2. Diagram: Add an arrow from Search Complete to BASE_PMTU Confirmation with the condition "PLPMTU confirmation failed".
2. Short description directly below the diagram: Use a ordered list (with numbers) instead of an unordered list to better express the sequence of actions in a phase.
3. Remove parts in the text where a phase transition is described that is not in the diagram (e. g. "entering the BASE_PMTU Confirmation" in  5.2.2. Search Phase).
4. Remove subsection "5.2.2.1. Resilience to Inconsistent Path Information" and merge its content into section "5.4.3. Resilience to Inconsistent Path Information".
5. Move subsection "5.2.4.1. Robustness to Inconsistent Path" to section "5.4. Search to Increase the PLPMTU" in order to simplify the high level overview.

I will fix these issues, if that's OK for you.

**Comment by gorryfair** [comment]
Point {1} - Sure. The state then is exited by confirming the base PMTU.
Point {2} - If you thing it makes it clearer, add.
Point {3} - We were trying to identify components not ordering.
Point {4} - Not sure - Can you do the rest and ask again?
Point {5} - This would be OK. The resilience is an aspect of search.
Point {6} - This isn't correct, the robustness to inconsistencies needs to be a part of the error processing.

**Comment by msvoelker** [comment]
I added this sentence right before the phase diagram figure.

> This section aims to give a higher level view of the DPLPMTUD method than the States section does. For more details see Section 5.3.

Point (1) (2)
I changed the diagram as discussed, but couldn't stop then. I did also a redesign (top to bottom flow), changed the name BASE_PMTU Confirmation to Base (since it also checks connectivity besides BASE_PMTU confirmation), and added a transition from Search Complete to Search. Please have a look at it.

Point (3)
It reads partly like a sequence for me. I think it is because of the word _then_. Do you mind, if I change the wording, for example, from

> BASE_PMTU Confirmation
> * Connectivity is confirmed.
> * DPLPMTUD confirms that BASE_PMTU is supported across the network path.
> * DPLPMTUD then enters the search phase.

to

> Base
> * Confirms connectivity.
> * Confirms that BASE_PMTU is supported across the network path.
> * Enters Search phase on success.
> * Enters Error phase on failure.

Point (4)
The new transitions in the phase diagram almost obsoletes this point.

Point (5)
I did the merge.

Point (6)
I agree in that section "5.4. Search to Increase the PLPMTU" isn't a good place for it. But I think the Phase section isn't either. Since I currently don't know a better place, I leave it where it is.

**Comment by adventureloop** [comment]
The phases section now only describes the changes between phases. Please check if changes are required and suggest text in a new issue.
