### ISSUE TITLE
More details in state description

### ISSUE THREAD

**Issue by msvoelker** [nplab/plpmtud#5]
I think we should add more details in the description of the states. For example, the description of the BASE state contains:

> The state is also left when the PROBE_COUNT reaches MAX_PROBES or a received PTB message is validated. This causes the PL sender to enter the ERROR state.

This does not mention the PTB_SIZE value. I extended the condition at the arrow in the state diagram to make that clearer. However, I think we should add more details in the description to make that clear without looking in the diagram. OK?

**Comment by gorryfair** [comment]
I don't understand the question, what do you expect to test for PTB_SIZE?

**Comment by msvoelker** [comment]
> I don't understand the question, what do you expect to test for PTB_SIZE?

You mean we switch to ERROR state no matter what value PTB_SIZE has?
Mmhh... That sounds fair in this state, but what if we are in SEARCHING. The text there also contains 

> a received PTB message is validated

without mentioning the PTB_SIZE value. In my opinion it makes a difference if PTB_SIZE < PLPMTU or PLPMTU = PTB_SIZE. 

I think we shouldn't leave SEARCHING when PLPMTU < PTB_SIZE. I opened issue #6 for that.

**Comment by gorryfair** [comment]
Base transitions to error when the base size can't be supported. This does not depend on the PTB (the error needs to be ignored because the sender cannot complete a check that the base size has worked.).

**Comment by adventureloop** [comment]
Can you check if this is still outstanding and create a new issue with old/new text
