### ISSUE TITLE
Use of PTB Messages inconsistent

### ISSUE THREAD

**Issue by msvoelker** [nplab/plpmtud#6]
Section 4.4.2. Use of PTB Messages tells us to do not update PLPMTU directly upon a PTB message reporting a MTU of PLPMTU < PTB_SIZE < PROBED_SIZE. The state diagram on the user hand tells us to transition from SEARCHING to SEARCH_COMPLETE state upon such a PTB message.

In my opinion we should do what section 4.4.2 says and change the state diagram, OK?

**Comment by gorryfair** [comment]
Aha - yes. Use of PTB Messages does not update PLPMTU directly upon a PTB message reporting a MTU of PLPMTU < PTB_SIZE < PROBED_SIZE. That seems correct, the middle in the transition description should be removed.  The state machine stays in the SEARCHING state (issuing a new probe packet).

Please suggest an update to the diagram.

**Comment by msvoelker** [comment]
Done
